export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HR = 'HR',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  SECURITY_GUARD = 'SECURITY_GUARD'
}

export enum RequestStatus {
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_HR = 'PENDING_HR',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}

export enum RequestType {
  LEAVE = 'LEAVE',
  EXIT = 'EXIT'
}

export enum GatePassStatus {
  ACTIVE = 'ACTIVE',
  USED = 'USED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum ExitStatus {
  PENDING = 'PENDING',
  EXITED = 'EXITED'
}

export enum ReturnStatus {
  PENDING = 'PENDING',
  RETURNED = 'RETURNED',
  LATE_RETURN = 'LATE_RETURN'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  ON_LEAVE = 'ON_LEAVE',
  ON_EXIT_PERMISSION = 'ON_EXIT_PERMISSION',
  HALF_DAY = 'HALF_DAY'
}

export enum NotificationType {
  INFO = 'INFO',
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  GATE_PASS_GENERATED = 'GATE_PASS_GENERATED',
  LATE_RETURN_ALERT = 'LATE_RETURN_ALERT',
  GATE_EXIT_LOGGED = 'GATE_EXIT_LOGGED',
  GATE_RETURN_LOGGED = 'GATE_RETURN_LOGGED'
}
