export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  HR = 'HR',
  MANAGER = 'MANAGER',
  GM = 'GM',
  EMPLOYEE = 'EMPLOYEE',
  SECURITY_GUARD = 'SECURITY_GUARD'
}

export enum ConnectionType {
  REPORTING_MANAGER = 'REPORTING_MANAGER',
  HR_AUTHORITY = 'HR_AUTHORITY',
  GM_AUTHORITY = 'GM_AUTHORITY',
  HIGHER_AUTHORITY = 'HIGHER_AUTHORITY'
}

export enum ConnectionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  INACTIVE = 'INACTIVE',
  NEEDS_REASSIGNMENT = 'NEEDS_REASSIGNMENT'
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  PENDING_MANAGER = 'PENDING_MANAGER',
  PENDING_HR = 'PENDING_HR',
  PENDING_GM = 'PENDING_GM',
  PENDING_SUPER_ADMIN = 'PENDING_SUPER_ADMIN',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SENT_BACK = 'SENT_BACK',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  OVERDUE = 'OVERDUE'
}

export enum ApprovalAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SEND_BACK = 'SEND_BACK',
  ESCALATE = 'ESCALATE'
}

export enum RequestType {
  LEAVE = 'LEAVE',
  EXIT = 'EXIT'
}

export enum GatePassStatus {
  ACTIVE = 'ACTIVE',
  USED = 'USED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED'
}

export enum ExitStatus {
  PENDING = 'PENDING',
  EXITED = 'EXITED'
}

export enum ReturnStatus {
  PENDING = 'PENDING',
  RETURNED = 'RETURNED',
  LATE_RETURN = 'LATE_RETURN',
  OVERDUE = 'OVERDUE',
  CRITICAL = 'CRITICAL'
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  ON_LEAVE = 'ON_LEAVE',
  ON_EXIT_PERMISSION = 'ON_EXIT_PERMISSION',
  HALF_DAY = 'HALF_DAY'
}

export enum NotificationType {
  INFO = 'INFO',
  APPROVAL_REQUEST = 'APPROVAL_REQUEST',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  REQUEST_SENT_BACK = 'REQUEST_SENT_BACK',
  GATE_PASS_GENERATED = 'GATE_PASS_GENERATED',
  LATE_RETURN_ALERT = 'LATE_RETURN_ALERT',
  CRITICAL_ALERT = 'CRITICAL_ALERT',
  GATE_EXIT_LOGGED = 'GATE_EXIT_LOGGED',
  GATE_RETURN_LOGGED = 'GATE_RETURN_LOGGED',
  AUTHORITY_REQUEST = 'AUTHORITY_REQUEST',
  AUTHORITY_ACCEPTED = 'AUTHORITY_ACCEPTED',
  AUTHORITY_REJECTED = 'AUTHORITY_REJECTED',
  ESCALATION = 'ESCALATION',
  REMINDER = 'REMINDER'
}

export enum NotificationPriority {
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
